language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
script: ./vendor/bin/phpunit
before_script: composer install
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c0da2eb2407d237880c6
    on_success: always
    on_failure: always
    on_start: never
